GET http://localhost:4004/v2/odata/EMPLOYEE
# Accept: application/json

###
DELETE http://localhost:4004/v2/odata/EMPLOYEE(EMP_ID=1)


###
POST http://localhost:4004/v2/odata/EMPLOYEE
Content-Type: application/json

{
    "EMP_ID"         : 4,
    "EMP_NAME"       : "Kurvesh Patel",
    "EMP_AGE"        : "23",
    "EMP_MODULE_MODULE_ID"     : "",
    "EMP_IMG"    : "",
    "EMP_IMG_URL" : ""
}


###
GET http://localhost:4004/v2/odata/readModule(MODULE_TYPE='Technical')


###
GET http://localhost:4004/v2/odata/MODULE

###
POST http://localhost:4004/v2/odata/MODULE
Content-Type: application/json

{
    "MODULE_ID":3,
    "MODULE_NAME":"SAP Quality Management",
    "MODULE_CODE":"QM",
    "MODULE_TYPE":"Technical"
}

###
DELETE  http://localhost:4004/v2/odata/MODULE(MODULE_ID=61)